# Generated by Django 3.2.5 on 2021-07-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock1',
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_id',
            field=models.IntegerField(),
        ),
    ]
