# Generated by Django 3.2.7 on 2024-12-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20241122_0814'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='userprofile',
        #     name='user',
        # ),
        migrations.AlterField(
            model_name='stock',
            name='user_id',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('user_id', 'stock_id'), name='unique_user_stock'),
        ),
        # migrations.DeleteModel(
        #     name='UserProfile',
        # ),
    ]
